<?php echo $this->doctype() ?>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>

<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>

<?php echo $this->headLink() ?>
<?php echo $this->headStyle() ?>

<?php echo $this->headScript() ?>
</head>

<body lang="en">
<?php echo $this->layout()->content; ?>

<?php //$this->inlineScript()->appendFile('/js/jquery-1.9.1.min.js'); ?>

<?php echo $this->inlineScript() ?>
</body>
</html>
